### ISSUE TITLE
ffip-prune-patterns is not well defined for fd

### ISSUE THREAD

**Issue by ShuguangSun** [technomancy/find-file-in-project#101]
Windows 7,
Emacs 27.

For example: the  "*.d" in ffip-prune-patterns will match ".emacs.d" and exclude all files under subdirectory ".emacs.d/".
It should be "*.d$" and treat "d" as file extension.

No sure whether it is fd's issue under windows.

**Comment by redguardtoo** [comment]
fd use `glob pattern` for `-E` option, not regular expression.  See https://en.wikipedia.org/wiki/Glob_%28programming%29

The global pattern does match whole string. So `$` is not needed.

By default, `fd` ignore hidden directory (directory name start with DOT). You can use `ffip-rust-fd-extra-opts` to pass `-H`, but `-H` will override all `-E` patterns.

Anyway, it's `fd`'s problem. My code is fine.

**Comment by ShuguangSun** [comment]
Got it. Thanks.
