### ISSUE TITLE
ffip-patterns not working well with fd

### ISSUE THREAD

**Issue by jasonjckn** [technomancy/find-file-in-project#102]
emacs v27.x HEAD
 find-file-in-project-20180404.525

`
  (setq ffip-patterns '("*.clj"))
`

Found argument '-w' wasn't expected 
USAGE:
    fd [FLAGS/OPTIONS] ...

**Comment by xianghx** [comment]
star '*'  doesn't work.   maybe you can use ``.clj` or `clj`.  
or 
@redguardtoo make some changes on the ffip-patterns  or   ffip-prune-patterns regex *.clij to clj.

I try , but I not good at elisp.


fd -E ".git/*" -E ".svn/*" -E ".cvs/*" -E ".bzr/*" -E ".hg/*" -E "*.log" -E "bin/*" -E ".DS_Store/*" -E "tags" -E "TAGS" -E "GTAGS" -E "GPATH" -E "GRTAGS" -E "cscope.files" -E ".npm/*" -E ".tmp/*" -E ".sass-cache/*" -E ".idea/*" -E "*min.js" -E "*min.css" -E "node_modules/*" -E "bower_components/*" -E "*.png" -E "*.jpg" -E "*.jpeg" -E "*.gif" -E "*.bmp" -E "*.tiff" -E "*.ico" -E "*.doc" -E "*.docx" -E "*.pdf" -E "*.obj" -E "*.o" -E "*.a" -E "*.dylib" -E "*.lib" -E "*.d" -E "*.dll" -E "*.exe" -E ".metadata*" -E ".gradle/*" -E "*.class" -E "*.war" -E "*.jar" -E "*flymake" -E "#*#" -E ".#*" -E "*.swp" -E "*~" -E "*.elc" -E ".cask/*" -E "*.pyc" -c never -i -t f   -p  ".*-w jj"

**Comment by redguardtoo** [comment]
5691beb fd supports ffip-patterns now (Chen Bin)

Use glob pattern as usualy, I will handle the conversion of global pattern to regular expression.

**Comment by jasonjckn** [comment]
thanks!
