### ISSUE TITLE
find-file-in-project-at-point & open-another-window keyboard binding wrong type argument

### ISSUE THREAD

**Issue by bscipio** [technomancy/find-file-in-project#103]
In my .emacs I can successfully use:
`(global-set-key (kbd "M-0") 'find-file-in-project-at-point) `

but I have not been successful finding the correct syntax to set a keybinding to open file at point, but in another/new window.
I've tried various variations of:
`(global-set-key (kbd "M-1") '(find-file-in-project-at-point "open-another-window") `

but I usually get the error when attempting to use the shortcut:
`command-execute: Wrong type argument: commandp, (find-file-in-project-at-point open-another-window)`

I apologize for my lack of lisp commands/functions experience.
Thank you!

**Comment by redguardtoo** [comment]
`(global-set-key (kbd "M-1")  (lambda () (interactive) (find-file-in-project-at-point t))`

Or press `C-u M-0`.

**Comment by bscipio** [comment]
Perfect! Thank you!
