### ISSUE TITLE
void-variable i (issue in newest melpa-version, 20180704)

### ISSUE THREAD

**Issue by benjaminor** [technomancy/find-file-in-project#109]
After updating, compiling your package leads to the following error:

I don't know exactly what it is, but it seems to result from a recent commit, IMO. 

`Debugger entered--Lisp error: (void-variable i)
  eval-buffer(#<buffer  *load*-564396> nil "/home/ben/.emacs.d/elpa/find-file-in-project-20180704.2201/find-file-in-project-autoloads.el" nil t)  ; Reading at buffer position 5624
  load-with-code-conversion("/home/ben/.emacs.d/elpa/find-file-in-project-20180704.2201/find-file-in-project-autoloads.el" "/home/ben/.emacs.d/elpa/find-file-in-project-20180704.2201/find-file-in-project-autoloads.el" nil t)
  load("/home/ben/.emacs.d/elpa/find-file-in-project-20180704.2201/find-file-in-project-autoloads" nil t)
  package--activate-autoloads-and-load-path(#s(package-desc :name find-file-in-project :version (20180704 2201) :summary "Find file/directory and review Diff/Patch/Commit efficiently everywhere" :reqs ((ivy (0 10 0)) (emacs (24 3))) :kind nil :archive nil :dir "/home/ben/.emacs.d/elpa/find-file-in-project-20180704.2201" :extras nil :signed nil))
  package--load-files-for-activation(#s(package-desc :name find-file-in-project :version (20180704 2201) :summary "Find file/directory and review Diff/Patch/Commit efficiently everywhere" :reqs ((ivy (0 10 0)) (emacs (24 3))) :kind nil :archive nil :dir "/home/ben/.emacs.d/elpa/find-file-in-project-20180704.2201" :extras nil :signed nil) nil)
  package-activate-1(#s(package-desc :name find-file-in-project :version (20180704 2201) :summary "Find file/directory and review Diff/Patch/Commit efficiently everywhere" :reqs ((ivy (0 10 0)) (emacs (24 3))) :kind nil :archive nil :dir "/home/ben/.emacs.d/elpa/find-file-in-project-20180704.2201" :extras nil :signed nil) nil deps)
  package-activate(find-file-in-project)
  package-initialize()
  eval-buffer(#<buffer  *load*-259483> nil "/home/ben/.emacs.d/elisp/base.el" nil t)  ; Reading at buffer position 471
  load-with-code-conversion("/home/ben/.emacs.d/elisp/base.el" "/home/ben/.emacs.d/elisp/base.el" nil t)
  require(base)
  eval-buffer(#<buffer  *load*> nil "/home/ben/.emacs.d/init.el" nil t)  ; Reading at buffer position 1296
  load-with-code-conversion("/home/ben/.emacs.d/init.el" "/home/ben/.emacs.d/init.el" t t)
  load("/home/ben/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x25f085>)()
  command-line()
  normal-top-level()
`

**Comment by redguardtoo** [comment]
fixed in v5.6.8
