### ISSUE TITLE
Similar file names are not sufficiently uniquified

### ISSUE THREAD

**Issue by paulcarey** [technomancy/find-file-in-project#11]
To reproduce:

    lein new foo
    cd foo
    git init
    echo 'src' > src/foo/bar.clj
    echo 'test' > test/foo/bar.clj
    emacs

Invoking ffip with bar shows two results - both named `foo/bar.clj` - but as far as I can see it's only possible to choose one. I can only open src/foo/bar.clj.

**Comment by redguardtoo** [comment]
turn on the full path flag by default to work around this issue for now. I will working on this issue later.

**Comment by redguardtoo** [comment]
I'm satisfied with current solution, path is important to filter candidates, so there is no reason to hide the path.
