### ISSUE TITLE
more unit test, and CI 

### ISSUE THREAD

**Issue by redguardtoo** [technomancy/find-file-in-project#111]
as title

**Comment by redguardtoo** [comment]
Hi, @technomancy 
Could you enable CI at https://travis-ci.org/account/repositories ?
I already write unit test. But I can't access this project.

**Comment by technomancy** [comment]
Sure thing; looks like it's running now:

https://travis-ci.org/technomancy/find-file-in-project/builds/509016690

**Comment by redguardtoo** [comment]
Thank you.
