### ISSUE TITLE
A sample .dir-locals.el correction

### ISSUE THREAD

**Issue by tang-junjie** [technomancy/find-file-in-project#113]
Hi,

I think there is a mistake in the sample code of .dir-locals.el where the comment ";; ingnore directory ".tox/" should be ";; Do NOT ignore directory ".tox/ and the comment ";; Do NOT ignore directory "bin/" should be ";; ignore directory "bin/", or leave the comment as it is but swap the delete in the code.

Thanks,
Junjie Tang

**Comment by redguardtoo** [comment]
Thanks I'll have a look

**Comment by tang-junjie** [comment]
By reference to the sample .dir-locals.el code, I am trying to have ffip to exclude elpa folder and it does not seem to work, not sure what I am doing wrong, here's the code I use, thanks for help!

(setq ffip-prune-patterns `("*/elpa/*" ,@ffip-prune-patterns))

**Comment by redguardtoo** [comment]
`*/elpa/*`, wild cards used  by GNU tools.

**Comment by tang-junjie** [comment]
i've figured it out, it works now, thanks a lot! 👍
