### ISSUE TITLE
Is 0c48407 or 83c9384 intended as 5.7.0?

### ISSUE THREAD

**Issue by sten0** [technomancy/find-file-in-project#114]
Hi @redguardtoo 

I noticed that there is a delta between master and 5.7.0, and a colleague pointed out that 5.7.0 was a detached tag.  Is 0c48407 or 83c9384 intended as 5.7.0?  If there's not a new release before the end of January this one will be the one shipped in Debian buster, so I wanted to check which commit was intended as 5.7.0.

```
* 83c9384 (upstream-vcs/master) could ignore directory and file separately
| * 0c48407 (tag: 5.7.0) could ignore directory and file separately
|/  
* a3d89bc documenation
* 1c54325 (tag: 5.6.8) fixed a few issues
```

Thanks again for maintaining find-file-in-project, it's super useful! :-)
Nicholas

**Comment by redguardtoo** [comment]
My mistake. Fixed. Thanks. I fixed the issue.

**Comment by sten0** [comment]
Thanks!  I've updated the Debian package.
