### ISSUE TITLE
Version 6.0.0 doesn't show list of files on Emacs 27.1

### ISSUE THREAD

**Issue by aidin36** [technomancy/find-file-in-project#123]
Today I upgraded to `6.0.0`, and it no longer shows the list of files when I execute `find-file-in-project`. I downgrade to `5.7.13` and it works fine.

Hopefully, the following screenshot clarifies what I mean.

I'm using Emacs 27.1, on a Gnu/Linux Mint 20 OS (based on Ubuntu 20.04). And if it's related, `ivy` is `0.13.0`.
I tried installing `find-file-in-project` both from MELPA and by copying the `.el` file into my `load-path`. Both methods had the same result.

Let me know if you need more info.

![Screenshot](https://user-images.githubusercontent.com/3810651/104243259-2f130c00-54c5-11eb-98ab-a0209872a7a4.png)

**Comment by redguardtoo** [comment]
since 6.0.0. the dependency on `ivy` is removed.  Install `ivy` and insert `(ivy-mode 1)` into your `~/.emacs`.

**Comment by aidin36** [comment]
Oh, I didn't notice it supports different completion frameworks. I use `helm` and it's even cooler to use `find-file-in-project` with `helm`!

I see you just updated the README file. I suggest mentioning it in the `install` or `setup` part. Mentioning that having `helm`/`ivy`/etc mode enabled will causes `find-file-in-project` to use that completion framework. It would be useful for people like me who are not very advanced in Emacs configs (:

**Comment by redguardtoo** [comment]
`(helm-mode 1)` is enough.
