### ISSUE TITLE
ffip-limit is too low

### ISSUE THREAD

**Issue by eallik** [technomancy/find-file-in-project#20]
The value 512 for the `ffip-limit` variable is extremely low. I just spent about half an hour to try to figure out why almost none of my project files are being displayed (it's a Scala+Java project).

Is there a particular reason this value is so low? Why does there have to be a limit in the first place? How about re-running the `find` command once the user types a search criteria after having interactively entered `ffip`? Because the way it currently works is really really confusing an unexpected.

**Comment by redguardtoo** [comment]
by default, there is no limit now, unless you assign a non-zero value to ``ffip-limit`, please upgrade to 3.4
