### ISSUE TITLE
Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by bw2** [technomancy/find-file-in-project#21]
I put find-files-in-project.el into ~/.emac.d and added 

(global-set-key (kbd "C-x f") 'find-file-in-project)

to ~/.emacs 

When I type `C-x f` I get the error:
`Wrong type argument: stringp, nil`

My emacs version is:
GNU Emacs 22.1.1 (mac-apple-darwin)

**Comment by technomancy** [comment]
You'll need a newer version for this; at least 23.
