### ISSUE TITLE
the find option "-type d -a" is unnessary.

### ISSUE THREAD

**Issue by redguardtoo** [technomancy/find-file-in-project#24]
for example, in a html5 project, there is no way I could exclude "*.min.js"

**Comment by technomancy** [comment]
Sorry, unfortunately I don't have the time to maintain this project at
this point. I would be happy to hand off maintainership to someone else
interested in keeping the project moving forward.

**Comment by redguardtoo** [comment]
got, I can take over this project.
What's the process to take over?

**Comment by technomancy** [comment]
If you have an account on Marmalade I can add upload permissions there.

Unfortunately Marmalade is refusing to load right now, so it will have
to wait till it comes back up. I can give you commit rights on GitHub though.

**Comment by redguardtoo** [comment]
Thanks, looks I can commit now

**Comment by magnars** [comment]
I'm using this actively, so glad to see it get some love. :+1:
