### ISSUE TITLE
Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by justinwyssgallifent** [technomancy/find-file-in-project#34]
I'm attempting to search a github repository on a mac and this is the result I'm getting:
Wrong type argument: stringp, nil
Google reveals this error arose once in 2008 but the fix that I found doesn't seem to apply here since the code has undergone so many revisions.

**Comment by redguardtoo** [comment]
what's the fix? besides, steps to reproduce the issue.

**Comment by justinwyssgallifent** [comment]
Turns out that emacs must have ido mode enabled.  This seemed to resolve the issue.

**Comment by redguardtoo** [comment]
I will a new UI for the find-file-in-project in the future
