### ISSUE TITLE
initial prompt very slow to show

### ISSUE THREAD

**Issue by benzitohhh** [technomancy/find-file-in-project#47]
Hi there,

thanks for your work on this project - it is amazing and I use it every day.

But... since version 3.6, the initial prompt takes a very long time to show.

For example, for a project with 60k files, `M-x find-file-in-project` takes about 20 seconds before the prompt is shown. Even when I exclude certain dirs with the `ffip-find-options` (i.e. mainly build and dependency artifiacts), and the results are restricted to a few hundred files, it still takes 20 seconds for the initial prompt to show.

For a project with only a few files, the initial prompt shows quickly though.

Previously I was using ffip with `ido-mode` (not `swiper`) and `flx-ido`. I have tried disabling these, but ffip still runs very slowly.

I love this package, but until the speed is fixed I need to downgrade to version 3.5

Any help would be really appreciated - thanks!

Ben

**Comment by redguardtoo** [comment]
yes, it's because I use the --iwholename to  match the part of path, that's slower than search the file name only, I will restore to the original original algorithm and make the new algorithm optional only

**Comment by benzitohhh** [comment]
Ok great thanks.

Yes, I'm using ffip with ido (and flx-ido).

I prefer the ido ui to swiper. And the "fuzzy matching" on flx-ido is really useful, matches my crappy spelling mistakes, for example "aquiEsition.js" will match "acquisition.js"

**Comment by redguardtoo** [comment]
what's your hardware spec? I tried linux kernel, about 50k files, before running ffip, I use `time find .` to test the performance of find, it's about 5 second. running ffip inside emacs is also about 5 seconds.

**Comment by redguardtoo** [comment]
`M-x eval-expression (setq ffip-debug t)`, then give the full command you use to search files.

**Comment by redguardtoo** [comment]
I think code is fine. just README has some wrong sample setup and default value of `ffip-prune-pattterns` is not 100% compatible with Find options. update to the latest code and check README.

**Comment by benzitohhh** [comment]
Ok I updated to latest version, and it works fine now. The initial prompt loads really fast, like it did before.

Also the `ffip-prefer-ido-mode` flag works great too.

Thanks so much for all your help @redguardtoo!

To answer your previous questions:

My hardware is a iMac 3.4 GHz Intel Core i5.

The debug trace of the command I was running is:
```
ffip--create-filename-pattern-for-gnufind called. rlt=
run cmd at /Users/benimmanuel/dev/src/cipher/frontend/: find . \( -iwholename "*/.git/*" -or -iwholename "*/.svn/*" -or -iwholename "*/.cvs/*" -or -iwholename "*/.bzr/*" -or -iwholename "*/.hg/*" -or -iwholename "*.log" -or -iwholename "*/bin/*" -or -iwholename "*/.DS_Store/*" -or -iwholename "*/tags" -or -iwholename "*/TAGS" -or -iwholename "*/GTAGS" -or -iwholename "*/GPATH" -or -iwholename "*/GRTAGS" -or -iwholename "*/cscope.files" -or -iwholename "*min.js" -or -iwholename "*min.css" -or -iwholename "*/node_modules/*" -or -iwholename "*/bower_components/*" -or -iwholename "*.png" -or -iwholename "*.jpg" -or -iwholename "*.jpeg" -or -iwholename "*.gif" -or -iwholename "*.bmp" -or -iwholename "*.tiff" -or -iwholename "*.doc" -or -iwholename "*.docx" -or -iwholename "*.pdf" -or -iwholename "*.obj" -or -iwholename "*.o" -or -iwholename "*.a" -or -iwholename "*.dylib" -or -iwholename "*.lib" -or -iwholename "*.d" -or -iwholename "*.dll" -or -iwholename "*.exe" -or -iwholename "*/.metadata*" -or -iwholename "*/.gradle/*" -or -iwholename "*.class" -or -iwholename "*.war" -or -iwholename "*.jar" -or -iwholename "*flymake" -or -iwholename "*/#*#" -or -iwholename ".#*" -or -iwholename "*.swp" -or -iwholename "*~" -or -iwholename "*.elc" -or -iwholename "*/.cask/*" -or -iwholename "*.pyc" \) -prune -o -type f    -not -iwholename '*/frontend/target/*' -not -iwholename '*target/scala-*' -not -iwholename '*target/universal*' -not -iwholename '*/.target/*' -not -iwholename '*/.build/*' -not -iwholename '*/build/*' -print
```

**Comment by redguardtoo** [comment]
cool
