### ISSUE TITLE
Possible wrong format in README.org regarding .dir-locals.el

### ISSUE THREAD

**Issue by esquellington** [technomancy/find-file-in-project#49]
In README.org, the syntax suggested in the following paragraph

Here is a sample .dir-locals.el,
((nil . ((ffip-project-root . "~/projs/PROJECT_DIR")
         (ffip-find-options "-not -size +64k -not -iwholename '*/dist/*'")
         (ffip-patterns '("*.html" "*.js" "*.css" "*.java" "*.xml" "*.js"))
         (ffip-prune-patterns '("*/.git/*" "*/node_modules/*" "*/index.js"))
         )))

Results in a "nothig found" message when running find-file-in-project (tested in Ubuntu 14.04 and Windows7 with Emacs 24.3)

I've corrected it using the following syntax in .dir-locals.el, which seems the correct according to emacs doc:
((nil .
      ((ffip-project-root . "~/project_root_dir")
       (ffip-patterns . ("*.h" "*.cpp"))
       (ffip-prune-patterns  . ("*/LOCAL/*" "*/DATA/*" "*/bin/*" "*/.bzr/*" "*/.hg/*"))
       )))

Otherwise ffip works great, thanks for such a useful package.

   Oscar

**Comment by redguardtoo** [comment]
thanks, I fixed the README. besides, you can `M-x ffip-create-project-file` to create sample .dir-locals.el now.
