### ISSUE TITLE
ffip project-dir

### ISSUE THREAD

**Issue by habamax** [technomancy/find-file-in-project#50]
Is it possible to give find-file-in-project a parameter to start looking for files in specific project?
What I would like to achive is to use ivy-read with predefined projects to open  file from the selected one.

I guess it could be done by cd'ing into selected project dir and start ffip (wrapped in one action function) but maybe threre is a better way?

**Comment by redguardtoo** [comment]
check README, you can change project root directory manually

**Comment by habamax** [comment]
I have tried in *scratch* buffer 2 mockups:
```
(progn
  (cd (ivy-read "Select project:" '("~/Projects/Test ground" "~/.emacs.d" "~/org")))
  (ffip))

(progn
  (setq ffip-project-root (ivy-read "Select project:" '("~/Projects/Test ground" "~/.emacs.d" "~/org")))
  (ffip))
```

Both works. Although per-directory settings are ignored (.dir-locals.el in selected project dir) which is sad.

**Comment by redguardtoo** [comment]
per directory setup works for other commands, ffip is written by technomancy, I've not touched it for ages. `find-file-in-project-by-selected` is recommended. I will look into ffip.
