### ISSUE TITLE
improve ffip-project-root function to use current directory when project root is not available.

### ISSUE THREAD

**Issue by stardiviner** [technomancy/find-file-in-project#51]
As the title said. Sometimes I just want to search files in current directory.
The default `ffip-project-root` function should be smart on this.

**Comment by redguardtoo** [comment]
Can you give more details? why you need search file in current directory?

**Comment by stardiviner** [comment]
For example, when I'm editing a ruby source code file which isn't in git managed. Then I try to search a file named something like image file or text file or something else.

**Comment by redguardtoo** [comment]
check README about `.dir-locals.el`, at minimum, you just need setup variable `ffip-project-root`.

**Comment by stardiviner** [comment]
I modified the default function `ffip-project-root-function` to this:

```lisp
(defun ffip-project-root ()
    "Return the root of the project."
    (let ((project-root (or ffip-project-root
                            (if (functionp ffip-project-root-function)
                                (funcall ffip-project-root-function)
                              (if (listp ffip-project-file)
                                  (cl-some (apply-partially 'locate-dominating-file
                                                            default-directory)
                                           ffip-project-file)
                                (locate-dominating-file default-directory
                                                        ffip-project-file))))))
      (or project-root
          (progn (message "No project was defined for the current file.")
                 "."
                 ;; nil
                 ))))
```

And set `ffip-project-root-function` to `ffip-project-root`:

```lisp
(setq ffip-project-root-function ffip-project-root)
```

**Comment by redguardtoo** [comment]
The simpler solution:
```lisp
(defun find-file-cwd ()
  (interactive)
  (let ((old-dir ffip-project-root))
    (setq ffip-project-root default-directory)
    (find-file-in-project)
    (setq ffip-project-root old-dir)))
```

**Comment by stardiviner** [comment]
This function will always use current directory, and also affect other buffers.

**Comment by redguardtoo** [comment]
You can define `ffip-project-root-function` which is nil by default.

**Comment by redguardtoo** [comment]
That's actually a good idea, and not hard to implement.

**Comment by redguardtoo** [comment]
fd512fc find file in current directory (Chen Bin)
