### ISSUE TITLE
use find-file-in-project can not find root

### ISSUE THREAD

**Issue by code-moritz** [technomancy/find-file-in-project#52]
OS: Msys2 64bit
emacs : 24.5 64bit

In a source code directory, i am already create the gtags db. and startup the emacs and use "find-file-in-project" command find some source files. 

the emacs mini buffer show:

`
No project was defined for the current file.

ffip-project-search: No project root found
` 

![ggtags-error](https://cloud.githubusercontent.com/assets/6115325/13773781/158f5eae-ead6-11e5-9b46-0ee3009b63bb.png)

**Comment by code-moritz** [comment]
Additional:
The  find-file-in-project should support Msys2 and MinGW *NIX emulate tools

**Comment by redguardtoo** [comment]
check README， gtags is never mentioned. The easiest way is create dir-locals.el in root directory. I already provided a sample.

besides, find-file-in-proeject support msys2 from the beginning.

**Comment by code-moritz** [comment]
@redguardtoo In my enviroment the command : find-file-in-proeject show error. 'can not find cygwin64binfind'. 
I view the find-file-in-proeject lisp source file. i found the lisp support cygwin and not support  msys2. 

![find](https://cloud.githubusercontent.com/assets/6115325/13800249/558ecabc-eb62-11e5-9cb8-9f63354f19fc.png)

Today morning, i try to modify the configure file according your suggest. but it is still failure. 
whey the find-file-in-proeject in linux or cygwin work fine?

**Comment by redguardtoo** [comment]
Customize `ffip-find-executable`, if it's nil, the guess process try to help

**Comment by redguardtoo** [comment]
c:\msys32\usr\bin\find.exe

**Comment by redguardtoo** [comment]
c91547e support msys2 (Chen Bin)

**Comment by code-moritz** [comment]
@redguardtoo  Yesterday FFIP 4.7 package have a critical  issues. 
today morning, i try to upgrade the find-file-in-project package. 
when i reopen emacs and use "fine-file-in-project " command find source code. 
but the feature have stop work, the eacs mini buffer show:bash: nil: command not found and no project root found. 
 
I guess the issues was merged at 4.7 source code. 

the cygwin and linux platform have the same issues. 

Best regards.
Thank you.

**Comment by code-moritz** [comment]
@redguardtoo 
I have already find the reason of the issues.

===================================
The  statement line has some problem. the author want to find the executable file and return it path. actually , it should true when it return exe file path. 
but here false and return the file path, the next step can't run a not exist file. 

i try to modify the statement ; 
`319(defun ffip--guess-gnu-find-on-windows (driver path)
320  (let (rlt)
321    (message "1:rlt = %s" rlt)
322    (if t (executable-find (concat driver path))
323        (message " , driver=%s, path = %s"  driver path)
324        (setq rlt (concat driver path)))
325    (message "2:rlt = %s" rlt)
326    rlt))
`
it is ok now. thank you .

**Comment by code-moritz** [comment]
@redguardtoo 
i try to contribution the modify code. 

but the system show me: no right. 

how can i apply commit right?

**Comment by code-moritz** [comment]
@redguardtoo  The latest version at line number 326
if the platform is cygwin. the system_type is cygwin , is not windows_nt. 

so, if that, the ffip--guess-gnu-find-on-windows function will be not execute.

**Comment by redguardtoo** [comment]
cygwin emacs will find `gnu find` automatically. Only windows native version need cygwin or mysys's help.
