### ISSUE TITLE
ffip-create-project-file overwrites existing .dir-locals.el

### ISSUE THREAD

**Issue by technomancy** [technomancy/find-file-in-project#54]
This function seems redundant given that `add-dir-local-variable` exists, which plays nicely with existing files.

**Comment by redguardtoo** [comment]
This is a issue. The solution is ask user to confirm if she want to override the existing .dir-locals.el, if "NO" create a .dir-locals-from-ffip.el instead. So she can merge the content.

Some users from projectile prefer a project file.

**Comment by redguardtoo** [comment]
better solution is to read existing .dir-locals.el at first. Less UI is better UI.

**Comment by redguardtoo** [comment]
60b00cb respect existing .dir-locals.el v4.9 (Chen Bin)
