### ISSUE TITLE
manage all projects?

### ISSUE THREAD

**Issue by futurist** [technomancy/find-file-in-project#57]
Want to search a list of all my projects(include in remote), how to do that? didn't find it in API

The counterpart for this in projectile is `projectile-switch-project`

**Comment by redguardtoo** [comment]
ffip doesn't support multiple directory search yet. but I you use Linux/Mac, you can use `ln` to place all your project into one root directory.

**Comment by futurist** [comment]
That's ok with this solution, maybe it's better to add a variable for this special **project root dir**, and search ln from emacs?

**Comment by futurist** [comment]
Hope `ffip` could manage projects, find files in a single project is strong, but if it can manage multiple projects, it's awesome!

**Comment by futurist** [comment]
There's also one import note for above **project root dir** var, that it can omit the necessary for createing `.dir-locals.el` file, since some times it's annoying to answer yes or no when open files.

**Comment by redguardtoo** [comment]
what do u mean project root dir? what you want me to do?
