### ISSUE TITLE
Latest ffip broken when manually setting ffip-project-root

### ISSUE THREAD

**Issue by apresta** [technomancy/find-file-in-project#61]
I just updated ffip and it broke my use case (where I use my custom logic to set ffip-project-root instead of relying on VCS repositories).

Steps to reproduce:
- Create a folder with a couple of files, say "~/hello/foo" and "~/hello/bar"
- *This is important* Start emacs in another folder (say "~").
- Evaluate: (setq ffip-project-root "~/hello")
- M-x find-file-in-project (I use IDO, not sure if it matters).

You will notice two things:
1) A red ^ is appended to the currently selected file
2) When you try to visit a file (say "foo"), it will append to default-directory its path *relative to the project*, resulting in a non-existing path, i.e. "~/foo".

**Comment by redguardtoo** [comment]
4a848aa ffip works in ido-mode (Chen Bin)

Thanks for reporting the issue. Yes, this is ido-mode only issue.

I also updated code to make sure all commands supports ido-mode.

**Comment by apresta** [comment]
Thanks for the quick fix!
Does this also get rid of the appended "^" character? This happens in ido-mode even for git repositories (where ffip is still working fine).

**Comment by apresta** [comment]
FYI, I tested this by downloading the latest version from github (since it hasn't hit MELPA yet), and I still have the same issues.

**Comment by redguardtoo** [comment]
I think the "^" is actually ido feature. Don't know much about ido, check my ido setup. "^" disappear after applying my ido setup.

**Comment by apresta** [comment]
The "^" is not an ido feature, as it goes away if I downgrade ffip.
Both issues (the wrong file paths and the added "^") were introduced by this commit: https://github.com/technomancy/find-file-in-project/commit/080a5cffe1e6e3110f01e63bf8c3fe476fd0dea5

Please take a look at my instructions above to reproduce.

**Comment by redguardtoo** [comment]
0e1b189 more friendly UI for ido (Chen Bin)

**Comment by apresta** [comment]
I can confirm that this fixes the appearance issue, however the bigger problem remains: "M-x find-file-in-project" only works from the project root.
I haven't looked at the code, but I imagine you build the absolute path to be visited in this way:
  absolute path = project root + relative path (selected via Ido)
Somehow, what it ends up doing is instead:
  absolute path = default directory + relative path
which leads to a non-existing file.

**Comment by redguardtoo** [comment]
b69411d in ido-mode we use absolute path (Chen Bin)

**Comment by apresta** [comment]
Works, thanks for the speedy fix!
