### ISSUE TITLE
`ffip-project-root` error when used with `file-name-as-directory`

### ISSUE THREAD

**Issue by achitu** [technomancy/find-file-in-project#66]
Commit e660b45f055be7735957706767e956fa7cab0a8d introduced a bug:
When `ffip-project-root` variable is not set, `file-name-as-directory` will throw an error. I'm using `ffip-project-root-function` for project root.

`(and ffip-project-root (file-name-as-directory ffip-project-root)) `

or something similar will fix this.

**Comment by redguardtoo** [comment]
sorry, my bad
1ac2c0a fixed regression bug in 5.2.6 (Chen Bin)
