### ISSUE TITLE
completion using helm?

### ISSUE THREAD

**Issue by rdotdk** [technomancy/find-file-in-project#68]
Hi,

I can't find any information that this package supports helm completion. I have helm installed but when i install this package it installs ivy along with it. It either uses ivy or ido. Any plan to support helm completion? 

Thanks,
Hari

**Comment by redguardtoo** [comment]
I don't have plan to support helm though you can advice `ffip-completing-read` to use helm.

Helm is not as efficient as ivy in low spec machine. That's the major reason I switched from helm to ivy several years ago.

**Comment by rdotdk** [comment]
Thanks. I am used to helm, so i'll just use advice.

PS. Happy New Year :)
