### ISSUE TITLE
ffip can work with like .gitignore or like that?

### ISSUE THREAD

**Issue by xianghx** [technomancy/find-file-in-project#73]
How to work with .gitignore or something like it.
Too many files we don't need. and  I don't want to add it manual.
Such as, in the rustlang, we don't need target/, but other project maybe need it.

And other thing,  when we work start from emacs , in the` *scratch*`,  it doesn't work. 
Sometimes we  just want to open` default-directory (setq default-directory "~/.emacs.d")`.

**Comment by redguardtoo** [comment]
If you want to only find file under git control, the more efficient way is to use `git`.

Check `counsel-git` from `counsel`

**Comment by xianghx** [comment]
Thanks, I got it.
How to switch over different projects quickly inner emacs?  not termial way.
 I just don't want projectile, that's too heavy.

**Comment by redguardtoo** [comment]
There is no project concept in ffip, Usually I just `counsel-recentf` to switch to the recent file. After that file is opened the current project root is automatically setup.

**Comment by xianghx** [comment]
Thanks, in the meaning,  there is no recent project buffer too. Just use counsel-recentf to open recent buffer?

**Comment by redguardtoo** [comment]
No. The counsel-recentf can fuzzy matching the full path. Why you need a project name? A directory is naturally a project name.

**Comment by xianghx** [comment]
so many file have same name . for example, main.rs  etc.  
In the project, just type main. 
If not in project, need to type project name. This is very inconvenient.

Sometimes, we just want to search at under the  project root.

**Comment by redguardtoo** [comment]
It's impossible you place the file with same name under same directory.
 
Both counsel and ffip support fuzz search PATH (when I say path, I mean the directory PLUS file name).

Here are filter you can input for counsel and ffip:
~/proj1/subdir1/a.txt (input `j1 a`)
~/proj1/subdir2/a.txt (input `r2 a`)
~/proj2/subdir1/a.txt (input `j2 a`)

**Comment by xianghx** [comment]
My workflow:
1.  switch to project,  use counsel-recentf or find-file etc, 
2.  find file , use counsel-git or  find-file-in-project(not git) 
2.  I mean in the project, I want to jump to recently visited files in the project.

some projectile function:  
projectile-switch-to-buffer or projectile-recentf
projectile-find-other-file(Switch between files with the same name but different extensions.)
projectile-toggle-between-implementation-and-test

**Comment by redguardtoo** [comment]
I just use `counsel-recentf`, ivy will sort the candidates by accessed time.

counsel also has its own buffer commands.

You can also check `find-file-in-project-by-selected`, I'm too lazy to remember different commands. So I just use `find-file-in-project-by-selected`.

**Comment by xianghx** [comment]
Thank you again. I will try it.
