### ISSUE TITLE
ffip appears to ignore bin folder on my project?

### ISSUE THREAD

**Issue by bk322** [technomancy/find-file-in-project#74]
`ffip-find-options` is `""`. The project is "marked" by `.git` in it. On `find-file-in-project` in ivy output I see all files, but those found under `bin` folder.

**Comment by redguardtoo** [comment]
(setq ffip-prune-patterns (delete "*/bin/*" ffip-prune-patterns))

**Comment by bk322** [comment]
Great, thanks!
