### ISSUE TITLE
test suite fails with GNU Emacs 25.1.1

### ISSUE THREAD

**Issue by sten0** [technomancy/find-file-in-project#79]
Dear Chen Bin

Thank you for maintaining find-file-in-project, it seems to work well with emacs25.  That said, I believe that the tests need to be updated.

$ emacs -q --no-site-file -batch -l cl-lib -l ert -l ivy-mock.el -l ../find-file-in-project.el  -l general.el -l windows.el -f ert-run-tests-batch-and-exit
Running 5 tests (2017-08-22 14:40:04-0400)
Nothing found!
Test ffip-ffip-show-diff backtrace:
  (let ((fn-42 (function string=)) (args-43 (list (file-name-nondirect
  (let (files (ffip-diff-backends (quote ((with-temp-buffer (insert-fi
  (lambda nil (let (files (ffip-diff-backends (quote ((with-temp-buffe
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
  ert-run-test([cl-struct-ert-test ffip-ffip-show-diff nil (lambda nil
  ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test f
  ert-run-tests(t #[385 "\306\307\"\203G\211\211G\310U\203\211@\20
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("-l" "cl-lib" "-l" "ert" "-l" "ivy-mock.el" "-l" "..
  command-line()
  normal-top-level()
Test ffip-ffip-show-diff condition:
    (wrong-type-argument stringp nil)
   FAILED  1/5  ffip-ffip-show-diff
Find in tests/: .
Test ffip-test-ffip backtrace:
  (if (unwind-protect (setq value-15 ivy-read-called) (setq form-descr
  (let (form-description-16) (if (unwind-protect (setq value-15 ivy-re
  (let ((value-15 (cl-gensym "ert-form-evaluation-aborted-"))) (let (f
  (let (files) (setq ffip-project-root default-directory) (setq files 
  (lambda nil (let (files) (setq ffip-project-root default-directory) 
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
  ert-run-test([cl-struct-ert-test ffip-test-ffip nil (lambda nil (let
  ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test f
  ert-run-tests(t #[385 "\306\307\"\203G\211\211G\310U\203\211@\20
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("-l" "cl-lib" "-l" "ert" "-l" "ivy-mock.el" "-l" "..
  command-line()
  normal-top-level()
Test ffip-test-ffip condition:
    (ert-test-failed
     ((should ivy-read-called)
      :form ivy-read-called :value nil))
   FAILED  2/5  ffip-test-ffip
   passed  3/5  ffip-test-ffip-open-another
Test ffip-test-find-by-selected backtrace:
  (if (unwind-protect (setq value-2 (apply fn-0 args-1)) (setq form-de
  (let (form-description-4) (if (unwind-protect (setq value-2 (apply f
  (let ((value-2 (quote ert-form-evaluation-aborted-3))) (let (form-de
  (let ((fn-0 (function string-match-p)) (args-1 (list "ivy.el" (car f
  (let (files) (setq ffip-project-root default-directory) (setq files 
  (lambda nil (let (files) (setq ffip-project-root default-directory) 
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
  ert-run-test([cl-struct-ert-test ffip-test-find-by-selected nil (lam
  ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test f
  ert-run-tests(t #[385 "\306\307\"\203G\211\211G\310U\203\211@\20
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("-l" "cl-lib" "-l" "ert" "-l" "ivy-mock.el" "-l" "..
  command-line()
  normal-top-level()
Test ffip-test-find-by-selected condition:
    (ert-test-failed
     ((should
       (string-match-p "ivy.el"
                       (car files)))
      :form
      (string-match-p "ivy.el" "ivy-mock.el")
      :value nil))
   FAILED  4/5  ffip-test-find-by-selected
NOT windows native Emacs, nothing to test.
   passed  5/5  ffip-test-windows

Ran 5 tests, 2 results as expected, 3 unexpected (2017-08-22 14:40:19-0400)

3 unexpected results:
   FAILED  ffip-ffip-show-diff
   FAILED  ffip-test-ffip
   FAILED  ffip-test-find-by-selected
--

I ran the tests directly with -q and --no-site-file to eliminate as many variables as possible.  In my efforts to patch this I could at most get one more test to pass.

Sincerely,
Nicholas

**Comment by redguardtoo** [comment]
cb61762 fixed tdd, ffip-diff-* commands can use ido (Chen Bin)

**Comment by sten0** [comment]
Thank you for the quick fix!
