### ISSUE TITLE
It's need to wait 10s when execute find-file-in project

### ISSUE THREAD

**Issue by suteng** [technomancy/find-file-in-project#81]
It's need to wait 10s when execute find-file-in project.
The project file number is 30k.
Do I miss some configure to speed up the finding?

**Comment by redguardtoo** [comment]
What project, did you try `ffip-prune-patterns`

**Comment by redguardtoo** [comment]
`M-x find-file-in-project` is developed ages ago by other developers. It basically just lists file in project directory before filtering with lisp code. So it's slow in big projects.

Try other commands, as I suggested.
