### ISSUE TITLE
`ffip-project-root` error: stringp nil

### ISSUE THREAD

**Issue by huwei9527** [technomancy/find-file-in-project#82]
When `ffip-project-root` is `nil` and `default-directory` is not in the directory with VC, `find-file-in-project` will error with `stringp nil`.

It maybe caused by the code in `ffip-proct-root` function using `(file-name-as-directory ffip-project-root)`

**Comment by redguardtoo** [comment]
you have to set `ffip-project-root` or else I can't search file in `project`

**Comment by huwei9527** [comment]
I think it should give warning instead of throw out a error, otherwise it is hard to advice that function to set the `ffip-project-root` dynamicly

**Comment by redguardtoo** [comment]
make sense
