### ISSUE TITLE
`find-file-in-project-by-selected` ignores files or directories ending with `.d`

### ISSUE THREAD

**Issue by huwei9527** [technomancy/find-file-in-project#83]
When I find file in the directory contain `emacs.d` directory, `find-file-in-project-by-selected` does not return matched file in directory `emac.d`. After testing, I find that it will ignore anything that ends with `.d`, no matter it is a file or directory.

Is it my problem or new issue?

**Comment by redguardtoo** [comment]
Yes, see `ffip-prune-patterns`, you can change it.

**Comment by huwei9527** [comment]
@redguardtoo I see. Thanks
