### ISSUE TITLE
Suggestion:  fall-back could be the default-directory.

### ISSUE THREAD

**Issue by lawlist** [technomancy/find-file-in-project#86]
For those users who have not defined a project root directory, it may be helpful to set up the `default-directory` of wherever the user happens to be as the fall-back.  I admittedly did not read the source code and jumped right in expecting the `default-directory` or a prompt with that being the initial option if a project directory had not been defined.  Instead, the functions that use `file-name-as-directory` will generate errors due to a `nil` value for the root.  I went through the library and made my own fixes with things like `(and root (file-directory-p root) (file-name-as-directory root))`, but there are of course other ways like modifying `ffip-get-project-root-directory`, which I chose not to touch at this point in time.

Thank you for developing this useful library.

**Comment by redguardtoo** [comment]
Thanks for the suggestion.

I remember somebody suggested this before and there are already solutions. You can use  `M-x find-file-in-current-directory` or `M-x find-file-in-current-directory-by-selected` instead.
