### ISSUE TITLE
Please add a LICENSE or COPYRIGHT file, and/or add/update tests/* headers to use GPL-3+

### ISSUE THREAD

**Issue by sten0** [technomancy/find-file-in-project#87]
Hi Chen Bin,

Debian's FTP Masters asked me to clarify the licensing of ffip/test/*.  It seems tests/* are GPL-2+, which is compatible with GPL-3+ used in find-file-in-project.el, so long as one assumes that tests/* is implicitly relicenced as GPL-3+.  Would you please add a GPL-3+ LICENSE or COPYRIGHT file, and/or update tests/* headers to use GPL-3+?  Finally, it would also be very much appreciated if you would tag 5.4.5 with this change to make it 100% official :-)

Thank you!
Nicholas

**Comment by redguardtoo** [comment]
Can I delete the license claim in `test/*` and just add LICENSE file in root directory?

**Comment by sten0** [comment]
Thank you very much!
