### ISSUE TITLE
Error: No such file or directory no longer exists! [2 times]

### ISSUE THREAD

**Issue by SethArchambault** [technomancy/find-file-in-project#91]
When I'm on my server, running M-x find-file-in-project-by-selected yields this error:

````
File /scp:servername:/home/myuser/MyProject/sh: /usr/local/bin/zsh: No such file or directory no longer exists! [2 times]
````

**Comment by redguardtoo** [comment]
What's `/scp:servername:/home/myuser/MyProject/sh`

**Comment by ShuguangSun** [comment]
/scp: is tramp protocol.

It seems due to shell-command-to-string, I have raised a topic in emacs-dev 
[shell-command-to-string](http://lists.gnu.org/archive/html/emacs-devel/2018-01/msg00726.html)
It may be solved soon.

**Comment by redguardtoo** [comment]
Could tell me the exact steps to reproduce this issue?

**Comment by redguardtoo** [comment]
Can you test new code at https://github.com/technomancy/find-file-in-project/tree/work (Please note it's `work` branch!)

**Comment by ShuguangSun** [comment]
The new work branch solve the shell-command-to-string issue. 

My pull request "Make ffip-project-search Tramp-aware #93" can help to use right "find" excutable in remote side. Otherwise, if local windows and remoter nix-like, the default ffip-find-executable has full windows path "c:/.../find.exe" and it can't be recognized by remote server (e.g., linux).

**Comment by redguardtoo** [comment]
Are you still using Windows32? I intend to drop support for it.

**Comment by ShuguangSun** [comment]
Do you mean to drop support all Windows series? (win 7, 10, etc?)
My suggested change is minor and has no side effect for nix-like.

**Comment by redguardtoo** [comment]
drop XP/Vista. Only supports Wn7+

**Comment by redguardtoo** [comment]
7be14de ffip works with tramp (Chen Bin)
