### ISSUE TITLE
find-file-in-project-at-point doesn't handle full paths

### ISSUE THREAD

**Issue by bscipio** [technomancy/find-file-in-project#97]
`find-file-in-project-at-point` in v5.5.0 seems to handle find/opening files without absolute paths ok, but doesn't handle  absolute paths, or relative paths containing with ".." as expected.  

Given a a working file/folder structure:

    ├── main.txt
    ├── file1.txt
    └── somepath
        └── file2.txt

where I'm editing main.txt

    % cat main.txt
    line 1 file1.txt
    line 2 file2.txt
    line 3 /full_path/to_another/file3.txt
    line 4 ../../yet_another/file4.txt

Noting the references to external files to the working file/structure with full paths:  `file3.txt` & `file4.txt`

If the cursor was on a file3.txt in main.txt above,  I would desire the function to first use that full-path first to open it.  If file not found, then search for file by filename only (no path included) based on the path of main.txt. 

Likewise, If the cursor was on a file4.txt in main.txt above, I would desire the function to first resolve the relative path to file4.txt, assumed path defined relative to main.txt, & open it.  If not found, then search for file by filename only (no path) from location of main.txt path. 

Ideally, open the file if only 1 match is found, otherwise list possible choices in minibuffer.

Finally, if no files are found after searches, prompt to create it.

Thank you!
Updates to this function will make opening and editing various files that reference other files very efficient.

Reference:
[find file at point](https://www.gnu.org/software/emacs/manual/html_node/emacs/FFAP.html) will find the files with full paths ok.  However, it prompts to confirm opening file.   [This function](http://ergoemacs.org/emacs/emacs_open_file_path_fast.html)  address the confirmation issue, but it does not automatically search for files in main.txt directory.  So file2.txt would not be found given the folder/file structure above.

**Comment by redguardtoo** [comment]
Just double check,
- `M-x eval-expression (ffip-project-root)`, is the project root correct.
- Does `(setq ffip-match-path-instead-of-filename t)` solve the problem?

**Comment by bscipio** [comment]
- `M-x eval-expression (ffip-project-root)`, is the project root correct?
  - Yes
- Does `(setq ffip-match-path-instead-of-filename t)` solve the problem?
   - It does not.

I just added `(setq ffip-match-path-instead-of-filename t)` to scratch buffer, then `M-x eval-buffer`
and paths like file3 and file4 above are not found as before.  ( ffap did find them ).

**Comment by redguardtoo** [comment]
ad7d8e3 find-file-in-project-at-point can handle file with absolute path (Chen Bin)

The file creattion function is easy to implement.I think it should be defined outside of ffip.

```lisp
(defun my-create-file-at-point ()
  "Create file and necessary directory using path at point."
  (interactive)
  (let* ((f (thing-at-point 'filename)))
    (when (and f (yes-or-no-p (format "create %s?" f)))
      (shell-command-to-string (format "mkdir -p %s && touch %s"
                                       (file-name-directory f)
                                       f))
      (if (file-exists-p f) (find-file f)))))
```

**Comment by bscipio** [comment]
ad7d8e3 addresses the absolute path issue. Excellent. Thank you!
However it does not find files with relative paths defined with ".." 

See line 4 in `main.txt` from example original post, and:

> Likewise, If the cursor was on a file4.txt in main.txt above, I would desire the function to first resolve the relative path to file4.txt, assumed path defined relative to main.txt, & open it. If not found, then search for file by filename only (no path) from location of main.txt path.

Thanks again!

**Comment by redguardtoo** [comment]
The relative part (dot and slashes) is ignored. We only search file name and directory from project root.

**Comment by bscipio** [comment]
Thanks for your help so far! Great stuff.

Unfortunately, I fairly often have the case where one config file in one project may reference files in other projects/parent folders via  ".." .

I believe a function that combines features of following would be very useful/powerful:
-  **find-file-in-project-at-point** :  
    - Auto-find: **Yes**.    See example `line 2 file2.txt` in original post to auto-find from project root.
    - No confirmation prompt: **Yes**
    - Support ".."  relative paths: **No**
- [FFAP](https://www.gnu.org/software/emacs/manual/html_node/emacs/FFAP.html) 
    - Auto-find: **No**  
    - No confirmation prompt: **No**.   Unnecessary confirmation prompt.
    - Support ".."  relative paths: **Yes**
- [Open File Path Under Cursor w/o confirmation](http://ergoemacs.org/emacs/emacs_open_file_path_fast.html)  @xahlee's better FFAP.   
    - Auto-find: **No**
    - No confirmation prompt: **Yes**
    - Support ".."  relative paths: **Yes**

I wish I knew lisp better.

Questions:
1. Any recommendations out there that behave like `find-file-in-project-at-point` , but also support ".." parent folder relative paths?   
2. Should I open new issue for consideration of ".." relative paths (outside project root)?
3.  Close this issue or leave open? (probably depends on 2's answer)

Thanks again!

**Comment by redguardtoo** [comment]
If it's relative path, try to open it directly if file exists. If file not exists, search in current project.
aba912a try to open file with relative path directly if file exists (Chen Bin)

**Comment by bscipio** [comment]
With aba912a, this package is perfect for my needs. Thank you so much @redguardtoo!
